<div class="row trade-tracker" id="failBlock" style="margin-top: 15px;">
    <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3  "  >
        <div class="alert alert-danger" role="alert">
            So weird!!! But I can't handle your URL!
        </div>
    </div>
    <div class=" col-sm-12">
            <img class="img-responsive persona"
                 src="http://vignette2.wikia.nocookie.net/fallout/images/2/28/Unsafe_Working_Conditions.png/revision/latest?cb=20100828101442"
                >
    </div>
</div>