<div class="row trade-tracker">
    <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3  "  id="errorBlock">
        <div class="alert alert-warning" role="alert">
            It doesn't look like URL with XML!
        </div>
        <div class="text-center" style="margin-bottom: 15px;">
            <img
                src="http://vignette2.wikia.nocookie.net/fallout/images/e/e4/16_The_Wasteland_Survival_Guide.png/revision/latest?cb=20100325142029"
                class="img-responsive persona">
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4 col-md-offset-4 text-center">
        <form onsubmit="importXML(); return false;" action="#" method="get">
            <div class="form-group">
                <input required="required" type="url" id="url" class="form-control" placeholder="URL">
            </div>
            <button type="submit" id="btn" class="btn btn-default">Submit</button>
        </form>
    </div>

</div>