<div class="row">
    <div class="col-md-12  text-center">

        <img
            src="http://vignette1.wikia.nocookie.net/fallout/images/5/53/38_Paradigm_of_Humanity.png/revision/latest?cb=20100325144844"
            class="img-responsive persona">

        <h3>Welcome to Development Assessment for TradeTracker <small>Memory limit: <?= $memoryLimit ?></small></h3>
        <hr/>
        <h4>
            Please, provide URL with valid XML! <small>Like this one:</small>
        </h4>
        <div class="text-muted text-center" style="margin-bottom: 15px;">
            <?= $simpleURL ?> (<?= $sizeOfSimple ?>)
        </div>
    </div>
</div>

<?= $this->partial('application/index/partials/form.phtml'); ?>

<div class="row trade-tracker " id="productsBlock">
    <hr/>
    <div class="text-muted text-center">Here will be items</div>
</div>

<?= $this->partial('application/index/partials/success.phtml'); ?>
<?= $this->partial('application/index/partials/fail.phtml'); ?>
<?= $this->partial('application/index/partials/loading.phtml'); ?>

<a name="bottom"></a>

<script>
    <?= $this->partial('application/index/partials/handler.js'); ?>
</script>